### PR TITLE
Feature 12 finish timetable editing

### LINKED ISSUE #1: [Feature 4] Timetable Editing
With this feature, users will be able to edit timetables that they have generated and then be able to save these generated timetables.

### PR DESCRIPTION
**Pull request by michaelhsj**
The code on feature branch 12 is now considered complete, having implemented all 3 of the use cases in the timetable editor (remove course, add course, edit course).

To overview this feature's code structure, we have EditTimetableScreen acting as the primary view of the use case, with AddCourseMenu and AddSectionMenu being auxiliary views used while editing and adding new courses. EditTimetableScreen implements the EditTimetableView, a view interface that all of the use case's presenters update. The EditTimetableScreen has the ability to call the EditTimetableController. The controller holds references to several input boundaries (AddCourseInputBoundary, EditCourseInputBoundary, RemoveCourseInputBoundary), one for each of the three parts of the use case, which it will call by sending a EditTimetableRequestModel.

The input boundaries are all concretely implemented by corresponding interactors, each of which mutates a timetable object that it has reference to. The plan is for these interactors to implement Java's flow subscribers, allowing them to use the observer design pattern and update their timetable and session references whenever the user navigates between sessions and timetables. After mutating these timetables, an input boundary from the RetrieveTimetable use case is called, creating a TimetableModel which is added to the EditTimetableRequestModel, which itself is sent to the given sub-use case's output boundary.

Each sub-use case has its own presenter, implementing their corresponding output boundary. Each presenter has a unique success message and is responsible for telling the view interface (EditTimetableView) to display such a message and update the timetable it displays. It does this by converting the TimetableModel it was given into a TimetableViewModel using the class of static methods, ModelConverter, then passing the view model to the view. (We note that this does not violate Clean Architecture since the ModelConverter class is an interface adapter, putting it in the same layer as all presenters).

A description of the full specification of this use case can be seen in the specification markdown.

Note that the interface segregation principle has been applied several times in this use case: interactors implement input boundaries, which are slotted into controllers, the EditTimetableScreen implements the EditTimetableView, which is slotted into each presenter, and the presenters are implementations of a given use case's output boundary, which are used by the interactor.

One place for improvement is that each input and output boundary share the same request and response models, EditTimetableRequestModel and EditTimetableResponseModel, when it might be best to separate them into response and request models for editing, removing and adding courses to better fulfil the single responsibility principle. Furthermore, the add and edit course use cases should raise errors when the adding or editing courses would create a time conflict.

For the reviewer: there should only be a single error in the main method, which should be corrected once the timetable view branch is merged into main (and has its main method written up).

### CODE REVIEW

**Review by YahyaElgabra — DISMISSED** [review]
Your pull request adheres to clean architecture and SOLID principles very well, and its folder structure is well-organized. I noticed that quite a few of your changes were refractors, and that is pretty good for maintaining high-quality code.
However, I have a few comments on it:
1- While this is a minor code smell, you have excessive comments for even setters in some files!
2- I understand that this is only for testing purposed but you have a main function in your EditTimetableScreen which violated clean architecture principles, since you are done with testing it I recommend removing the main function.
3- I am not sure if this is a problem but GitHub flagged it, but according to https://unix.stackexchange.com/questions/18743/whats-the-point-in-adding-a-new-line-to-the-end-of-a-file, I think it is important to have it.
4- Your implementation of flow (observer pattern), is incomplete, but I understand that that's because you are waiting on my implementation of the publisher. I do want to say that onError and onComplete is not required for extending flow observer for it so since these function are empty I recommend removing them until you need them.
5- I am unfamiliar with gateways so I am afraid that I can't ensure their quality.
6- I also did not review files that I am certain are other people's use cases since they will be rendered obsolete once their owner sends their updated branches.
7- Finally, I'm hesitating on approving this pull request because of the error in the main method, but since you confirmed that this will surely be fixed once the timetable view branch is merged in, I will let it pass.

Aside from that, your code is great and uses multiple design patterns including dependency inversion, plan on implementing observer pattern. Good Job!

**Comment by michaelhsj** [comment]
I've since removed the excessive comments for the getters and setters (😅 sorry about that!), and removed the main method from EditTimetableScreen, so the imports on that class should be fixed now. Let me know if there are any issues left!

**Review by YahyaElgabra — DISMISSED** [review]
perfect, looks better now

**Review by YahyaElgabra — APPROVED** [review]
I'm not sure why files like EditTimetableScreen showed as new so I'll assume that they were just moved. The changed files do look clean, not so sure about having onComplete and onError though since they are not required but still empty so you could just omit them.
I noticed that there is extra tesitng, that's always welcome!

**Pull request merged**
