### PR TITLE
Feature 0: Entities

### LINKED ISSUE #9: [Feature 0] Base Features
Implementing crucial entities that will be used in all features.

### PR DESCRIPTION
**Pull request by michaelhsj**
Feature 0: Entities is almost complete. All entities that will be used by use cases currently in development are stored in main/java/entities.

The following entities are introduced:

- Timetables represent the timetable a student is using. It contains a list of Sections and its own session type.

- Sessions represent all courses offered during a given semester, and contain a HashMap from course names to CalendarCourses, as well as their own session type.

- Courses are abstract classes that have a title, course code, a session type, a breadth type, as well as a list of sections. 

- TimetableCourse is a concrete implementation of Course that, in addition to Course's functionality, have the added representation invariant of only having at most one tutorial, practical and lecture at a time. This course is used to represent the sort of course attendance a student has.

-  CalendarCourse is a concrete implementation of Course that represents all of the offered sections from a Course.

- Sections contain a section code, instructor name, and a list of blocks, and represents a section offered by a course that a student can attend (eg. a tutorial section or practical section).

- Blocks contain a day, start time and end time, and a room identifier, and represent a given block of time taken up by a section.

Furthermore, a collection of Constraints exist, and these will be used by a number of use cases when generating timetables.

A number of files have warnings or incomplete documentation and testing. Since this pull request exists for the sake of receiving feedback before the deadline, these will addressed in a future pull request.

### CODE REVIEW

**Review by Firebrandt — DISMISSED** [review]
This seems workable for the moment. Largely matches the CRC diagrams we agreed upon and does a reasonable job of implementing needed features. In particular, the entities for Block, Section, TimetableCourse and Timetable seem to be exactly what I expected of them (and I used them a bit). 

Good work! LGTM! Don't forget the cleanup. 

Some of the tests have a lot of basically boilerplate in there. We may wish to consider using @Before/ @BeforeClass, @After, @AfterClass to make it a little more readable. Or to use helpers for function setup, NGL.

**Review by Kai15116 — DISMISSED** [review]
It looks good in terms of functionality. As addressed in the request, we should work in future to add tests, add a comment, fix the warnings, and etc.

**Review by hanshhh — DISMISSED** [review]
Thanks. Great job sticking to our CRC model, it looks good for now, but we still have to deal with the code smell, some of the documentations ,and test cases for TimeTable entity soon this week.

**Review by Firebrandt — APPROVED** [review]
Whoops, nice catch.
See previous comment, which still holds since this merge is fairly minor (README editing).

**Pull request merged**
